# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 xcodeproj 'ByteDanceCampus_Weather.xcodeproj'
target 'ByteDanceCampus_Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteDanceCampus_Weather
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.1.0'
end
