//
//  ForecastHourlyBean.h
//
//  Created by cnatom on 2022/08/12.
//  Copyright © 2022年 ssr. All rights reserved.
//  天气预报ForecastHourlyBean
//  未来24小时天气预报
//  Code generated by jsonToOCModel https://json.im/
//

#import <Foundation/Foundation.h>

@interface ForecastHourlyBeanForecastHourlyHours : NSObject <NSCoding, NSCopying>

/*
 {
 "cloudCover": 0.71,
 "conditionCode": "MostlyCloudy",
 "daylight": false,
 "forecastStart": "2022-08-12T15:00:00Z",
 "humidity": 0.89,
 "precipitationAmount": 0.37,
 "precipitationChance": 0.28,
 "precipitationIntensity": 0.37,
 "precipitationType": "rain",
 "pressure": 1003.2,
 "pressureTrend": "rising",
 "snowfallIntensity": 0,
 "temperature": 25.87,
 "temperatureApparent": 29.35,
 "temperatureDewPoint": 23.95,
 "uvIndex": 0,
 "visibility": 18292.94,
 "windDirection": 109,
 "windGust": 13.77,
 "windSpeed": 6.61
 }
 */
@property (nonatomic, assign) double cloudCover;
@property (nonatomic, strong) NSString *conditionCode;
@property (nonatomic, assign) BOOL daylight;
@property (nonatomic, strong) NSString *forecastStart;
@property (nonatomic, assign) double humidity;
@property (nonatomic, assign) double precipitationAmount;
@property (nonatomic, assign) double precipitationChance;
@property (nonatomic, assign) double precipitationIntensity;
@property (nonatomic, strong) NSString *precipitationType;
@property (nonatomic, assign) double pressure;
@property (nonatomic, strong) NSString *pressureTrend;
@property (nonatomic, assign) double snowfallIntensity;
@property (nonatomic, assign) double temperature;
@property (nonatomic, assign) double temperatureApparent;
@property (nonatomic, assign) double temperatureDewPoint;
@property (nonatomic, assign) double uvIndex;
@property (nonatomic, assign) double visibility;
@property (nonatomic, assign) double windDirection;
@property (nonatomic, assign) double windGust;
@property (nonatomic, assign) double windSpeed;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastHourlyBeanForecastHourly : NSObject <NSCoding, NSCopying>

/*
 {
 "hours": [
 {
 "cloudCover": 0.71,
 "conditionCode": "MostlyCloudy",
 "daylight": false,
 "forecastStart": "2022-08-12T15:00:00Z",
 "humidity": 0.89,
 "precipitationAmount": 0.37,
 "precipitationChance": 0.28,
 "precipitationIntensity": 0.37,
 "precipitationType": "rain",
 "pressure": 1003.2,
 "pressureTrend": "rising",
 "snowfallIntensity": 0,
 "temperature": 25.87,
 "temperatureApparent": 29.35,
 "temperatureDewPoint": 23.95,
 "uvIndex": 0,
 "visibility": 18292.94,
 "windDirection": 109,
 "windGust": 13.77,
 "windSpeed": 6.61
 }
 ]
 }
 */
@property (nonatomic, strong) NSArray <ForecastHourlyBeanForecastHourlyHours *> *hours;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastHourlyBean : NSObject <NSCoding, NSCopying>

/*
 {
 "forecastHourly": {
 "hours": [
 {
 "cloudCover": 0.71,
 "conditionCode": "MostlyCloudy",
 "daylight": false,
 "forecastStart": "2022-08-12T15:00:00Z",
 "humidity": 0.89,
 "precipitationAmount": 0.37,
 "precipitationChance": 0.28,
 "precipitationIntensity": 0.37,
 "precipitationType": "rain",
 "pressure": 1003.2,
 "pressureTrend": "rising",
 "snowfallIntensity": 0,
 "temperature": 25.87,
 "temperatureApparent": 29.35,
 "temperatureDewPoint": 23.95,
 "uvIndex": 0,
 "visibility": 18292.94,
 "windDirection": 109,
 "windGust": 13.77,
 "windSpeed": 6.61
 }
 ]
 }
 }
 */
@property (nonatomic, strong) ForecastHourlyBeanForecastHourly *forecastHourly;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

