//
//  ForecastDailyModel.h
//
//  Created by cnatom on 2022/08/12.
//  Copyright © 2022年 ssr. All rights reserved.
//  天气预报ForecastDailyBean
//  每天的天气
//  Code generated by jsonToOCModel https://json.im/
//


#import <Foundation/Foundation.h>

@interface ForecastDailyModelForecastDailyDaysRestOfDayForecast : NSObject <NSCoding, NSCopying>

/*
 {
 "cloudCover": 0.78,
 "conditionCode": "Drizzle",
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-12T14:42:46Z",
 "humidity": 0.9,
 "precipitationAmount": 0.46,
 "precipitationChance": 0.4,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 104,
 "windSpeed": 6.36
 }
 */
@property (nonatomic, assign) double cloudCover;
@property (nonatomic, strong) NSString *conditionCode;
@property (nonatomic, strong) NSString *forecastEnd;
@property (nonatomic, strong) NSString *forecastStart;
@property (nonatomic, assign) double humidity;
@property (nonatomic, assign) double precipitationAmount;
@property (nonatomic, assign) double precipitationChance;
@property (nonatomic, strong) NSString *precipitationType;
@property (nonatomic, assign) double snowfallAmount;
@property (nonatomic, assign) double windDirection;
@property (nonatomic, assign) double windSpeed;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastDailyModelForecastDailyDaysOvernightForecast : NSObject <NSCoding, NSCopying>

/*
 {
 "cloudCover": 0.82,
 "conditionCode": "Rain",
 "forecastEnd": "2022-08-12T23:00:00Z",
 "forecastStart": "2022-08-12T11:00:00Z",
 "humidity": 0.91,
 "precipitationAmount": 8.49,
 "precipitationChance": 0.74,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 83,
 "windSpeed": 6.91
 }
 */
@property (nonatomic, assign) double cloudCover;
@property (nonatomic, strong) NSString *conditionCode;
@property (nonatomic, strong) NSString *forecastEnd;
@property (nonatomic, strong) NSString *forecastStart;
@property (nonatomic, assign) double humidity;
@property (nonatomic, assign) double precipitationAmount;
@property (nonatomic, assign) double precipitationChance;
@property (nonatomic, strong) NSString *precipitationType;
@property (nonatomic, assign) double snowfallAmount;
@property (nonatomic, assign) double windDirection;
@property (nonatomic, assign) double windSpeed;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastDailyModelForecastDailyDaysDaytimeForecast : NSObject <NSCoding, NSCopying>

/*
 {
 "cloudCover": 0.47,
 "conditionCode": "PartlyCloudy",
 "forecastEnd": "2022-08-12T11:00:00Z",
 "forecastStart": "2022-08-11T23:00:00Z",
 "humidity": 0.72,
 "precipitationAmount": 0.02,
 "precipitationChance": 0.19,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 124,
 "windSpeed": 5.6
 }
 */
@property (nonatomic, assign) double cloudCover;
@property (nonatomic, strong) NSString *conditionCode;
@property (nonatomic, strong) NSString *forecastEnd;
@property (nonatomic, strong) NSString *forecastStart;
@property (nonatomic, assign) double humidity;
@property (nonatomic, assign) double precipitationAmount;
@property (nonatomic, assign) double precipitationChance;
@property (nonatomic, strong) NSString *precipitationType;
@property (nonatomic, assign) double snowfallAmount;
@property (nonatomic, assign) double windDirection;
@property (nonatomic, assign) double windSpeed;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastDailyModelForecastDailyDays : NSObject <NSCoding, NSCopying>

/*
 {
 "conditionCode": "Drizzle",
 "daytimeForecast": {
 "cloudCover": 0.47,
 "conditionCode": "PartlyCloudy",
 "forecastEnd": "2022-08-12T11:00:00Z",
 "forecastStart": "2022-08-11T23:00:00Z",
 "humidity": 0.72,
 "precipitationAmount": 0.02,
 "precipitationChance": 0.19,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 124,
 "windSpeed": 5.6
 },
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-11T16:00:00Z",
 "maxUvIndex": 7,
 "moonPhase": "full",
 "moonrise": "2022-08-12T11:50:20Z",
 "moonset": "2022-08-11T21:03:14Z",
 "overnightForecast": {
 "cloudCover": 0.82,
 "conditionCode": "Rain",
 "forecastEnd": "2022-08-12T23:00:00Z",
 "forecastStart": "2022-08-12T11:00:00Z",
 "humidity": 0.91,
 "precipitationAmount": 8.49,
 "precipitationChance": 0.74,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 83,
 "windSpeed": 6.91
 },
 "precipitationAmount": 1.09,
 "precipitationChance": 0.49,
 "precipitationType": "rain",
 "restOfDayForecast": {
 "cloudCover": 0.78,
 "conditionCode": "Drizzle",
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-12T14:42:46Z",
 "humidity": 0.9,
 "precipitationAmount": 0.46,
 "precipitationChance": 0.4,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 104,
 "windSpeed": 6.36
 },
 "snowfallAmount": 0,
 "solarMidnight": "2022-08-11T16:19:49Z",
 "solarNoon": "2022-08-12T04:19:26Z",
 "sunrise": "2022-08-11T21:24:36Z",
 "sunriseAstronomical": "2022-08-11T19:43:17Z",
 "sunriseCivil": "2022-08-11T20:55:41Z",
 "sunriseNautical": "2022-08-11T20:20:44Z",
 "sunset": "2022-08-12T11:14:01Z",
 "sunsetAstronomical": "2022-08-12T12:55:03Z",
 "sunsetCivil": "2022-08-12T11:42:50Z",
 "sunsetNautical": "2022-08-12T12:17:45Z",
 "temperatureMax": 32.04,
 "temperatureMin": 21.19
 }
 */
@property (nonatomic, strong) NSString *conditionCode;
@property (nonatomic, strong) ForecastDailyModelForecastDailyDaysDaytimeForecast *daytimeForecast;
@property (nonatomic, strong) NSString *forecastEnd;
@property (nonatomic, strong) NSString *forecastStart;
@property (nonatomic, assign) double maxUvIndex;
@property (nonatomic, strong) NSString *moonPhase;
@property (nonatomic, strong) NSString *moonrise;
@property (nonatomic, strong) NSString *moonset;
@property (nonatomic, strong) ForecastDailyModelForecastDailyDaysOvernightForecast *overnightForecast;
@property (nonatomic, assign) double precipitationAmount;
@property (nonatomic, assign) double precipitationChance;
@property (nonatomic, strong) NSString *precipitationType;
@property (nonatomic, strong) ForecastDailyModelForecastDailyDaysRestOfDayForecast *restOfDayForecast;
@property (nonatomic, assign) double snowfallAmount;
@property (nonatomic, strong) NSString *solarMidnight;
@property (nonatomic, strong) NSString *solarNoon;
@property (nonatomic, strong) NSString *sunrise;
@property (nonatomic, strong) NSString *sunriseAstronomical;
@property (nonatomic, strong) NSString *sunriseCivil;
@property (nonatomic, strong) NSString *sunriseNautical;
@property (nonatomic, strong) NSString *sunset;
@property (nonatomic, strong) NSString *sunsetAstronomical;
@property (nonatomic, strong) NSString *sunsetCivil;
@property (nonatomic, strong) NSString *sunsetNautical;
@property (nonatomic, assign) double temperatureMax;
@property (nonatomic, assign) double temperatureMin;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastDailyModelForecastDaily : NSObject <NSCoding, NSCopying>

/*
 {
 "days": [
 {
 "conditionCode": "Drizzle",
 "daytimeForecast": {
 "cloudCover": 0.47,
 "conditionCode": "PartlyCloudy",
 "forecastEnd": "2022-08-12T11:00:00Z",
 "forecastStart": "2022-08-11T23:00:00Z",
 "humidity": 0.72,
 "precipitationAmount": 0.02,
 "precipitationChance": 0.19,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 124,
 "windSpeed": 5.6
 },
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-11T16:00:00Z",
 "maxUvIndex": 7,
 "moonPhase": "full",
 "moonrise": "2022-08-12T11:50:20Z",
 "moonset": "2022-08-11T21:03:14Z",
 "overnightForecast": {
 "cloudCover": 0.82,
 "conditionCode": "Rain",
 "forecastEnd": "2022-08-12T23:00:00Z",
 "forecastStart": "2022-08-12T11:00:00Z",
 "humidity": 0.91,
 "precipitationAmount": 8.49,
 "precipitationChance": 0.74,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 83,
 "windSpeed": 6.91
 },
 "precipitationAmount": 1.09,
 "precipitationChance": 0.49,
 "precipitationType": "rain",
 "restOfDayForecast": {
 "cloudCover": 0.78,
 "conditionCode": "Drizzle",
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-12T14:42:46Z",
 "humidity": 0.9,
 "precipitationAmount": 0.46,
 "precipitationChance": 0.4,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 104,
 "windSpeed": 6.36
 },
 "snowfallAmount": 0,
 "solarMidnight": "2022-08-11T16:19:49Z",
 "solarNoon": "2022-08-12T04:19:26Z",
 "sunrise": "2022-08-11T21:24:36Z",
 "sunriseAstronomical": "2022-08-11T19:43:17Z",
 "sunriseCivil": "2022-08-11T20:55:41Z",
 "sunriseNautical": "2022-08-11T20:20:44Z",
 "sunset": "2022-08-12T11:14:01Z",
 "sunsetAstronomical": "2022-08-12T12:55:03Z",
 "sunsetCivil": "2022-08-12T11:42:50Z",
 "sunsetNautical": "2022-08-12T12:17:45Z",
 "temperatureMax": 32.04,
 "temperatureMin": 21.19
 }
 ]
 }
 */
@property (nonatomic, strong) NSArray <ForecastDailyModelForecastDailyDays *> *days;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

@interface ForecastDailyBean : NSObject <NSCoding, NSCopying>

/*
 {
 "forecastDaily": {
 "days": [
 {
 "conditionCode": "Drizzle",
 "daytimeForecast": {
 "cloudCover": 0.47,
 "conditionCode": "PartlyCloudy",
 "forecastEnd": "2022-08-12T11:00:00Z",
 "forecastStart": "2022-08-11T23:00:00Z",
 "humidity": 0.72,
 "precipitationAmount": 0.02,
 "precipitationChance": 0.19,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 124,
 "windSpeed": 5.6
 },
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-11T16:00:00Z",
 "maxUvIndex": 7,
 "moonPhase": "full",
 "moonrise": "2022-08-12T11:50:20Z",
 "moonset": "2022-08-11T21:03:14Z",
 "overnightForecast": {
 "cloudCover": 0.82,
 "conditionCode": "Rain",
 "forecastEnd": "2022-08-12T23:00:00Z",
 "forecastStart": "2022-08-12T11:00:00Z",
 "humidity": 0.91,
 "precipitationAmount": 8.49,
 "precipitationChance": 0.74,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 83,
 "windSpeed": 6.91
 },
 "precipitationAmount": 1.09,
 "precipitationChance": 0.49,
 "precipitationType": "rain",
 "restOfDayForecast": {
 "cloudCover": 0.78,
 "conditionCode": "Drizzle",
 "forecastEnd": "2022-08-12T16:00:00Z",
 "forecastStart": "2022-08-12T14:42:46Z",
 "humidity": 0.9,
 "precipitationAmount": 0.46,
 "precipitationChance": 0.4,
 "precipitationType": "rain",
 "snowfallAmount": 0,
 "windDirection": 104,
 "windSpeed": 6.36
 },
 "snowfallAmount": 0,
 "solarMidnight": "2022-08-11T16:19:49Z",
 "solarNoon": "2022-08-12T04:19:26Z",
 "sunrise": "2022-08-11T21:24:36Z",
 "sunriseAstronomical": "2022-08-11T19:43:17Z",
 "sunriseCivil": "2022-08-11T20:55:41Z",
 "sunriseNautical": "2022-08-11T20:20:44Z",
 "sunset": "2022-08-12T11:14:01Z",
 "sunsetAstronomical": "2022-08-12T12:55:03Z",
 "sunsetCivil": "2022-08-12T11:42:50Z",
 "sunsetNautical": "2022-08-12T12:17:45Z",
 "temperatureMax": 32.04,
 "temperatureMin": 21.19
 }
 ]
 }
 }
 */
@property (nonatomic, strong) ForecastDailyModelForecastDaily *forecastDaily;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end

